// c:\codes\pricecalc\lib\features\history\data\repository.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'history_repository.dart';