// c:\codes\pricecalc\lib\features\group.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'data/data.dart';
export 'domain/domain.dart';
export 'presentation/presentation.dart';
